[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
cache_path = 'cache'

solc-version = "0.8.30"
optimizer = true
optimizer-runs = 10_000_000
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

fs_permissions = [{ access = "read-write", path = "./script/deployment/" }]